<?xml version="1.0"?>
<package format="3">
  <name>p3dx_slam</name>
  <version>0.1.0</version>
  <description>SLAM (slam_toolbox) and Gazebo simulation for Pioneer 3DX</description>
  <maintainer email="jcp@example.com">jcp</maintainer>
  <license>BSD-3-Clause</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>gazebo_ros</exec_depend>
  <exec_depend>robot_state_publisher</exec_depend>
  <exec_depend>joint_state_publisher</exec_depend>
  <exec_depend>slam_toolbox</exec_depend>
  <exec_depend>rviz2</exec_depend>
  <exec_depend>xacro</exec_depend>
  <exec_depend>p3dx_description_ros</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
